set-option -g default-shell /bin/zsh
set -g mouse on

#colors
#set -g default-terminal "screen-256color"
#set -ag terminal-overrides ",xterm-256color:RGB"
set -g default-terminal "screen-256color"

# remap prefix 
unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix
#set-option -g prefix C-_      # Ctrl+/
#set-option -g prefix2 M-z
#bind-key C-_ send-prefix
#bind-key M-z send-prefix -2

# reload config file 
bind r source-file ~/.tmux.conf \; display-message "Configuration reloaded."

# don't rename windows automatically
#set-option -g allow-rename off
#set-option -g automatic-rename off

# Shift arrow to switch windows
bind -n M-Left  previous-window
bind -n M-Right next-window

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Навигация по панелям 
bind -n M-h select-pane -L
bind -n M-l select-pane -R

# Set status bar color
set -g status-bg colour8
 
# customize how windows are displayed in the status line
set -g window-status-current-format "#[fg=colour8]#[bg=colour4]#[fg=colour7]#[bg=colour4] #I*|#[fg=colour7]#W #[fg=colour4]#[bg=colour8]"
set -g window-status-format "#[fg=colour232]#[bg=colour8]#I.#[fg=colour232]#W"
